image: fedora:rawhide

variables:
  DEPENDENCIES: gcc gcc-c++ glibc-devel make libxml2-devel glib2-devel
                automake autoconf gettext intltool git

build:
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    # Compile xdgmime
    - git clone https://gitlab.freedesktop.org/xdg/xdgmime.git
    - cd xdgmime
    - make
    - cd ..
    - mkdir build
    - cd build
    - XDGMIME_PATH=`pwd`/../xdgmime/ ../autogen.sh --disable-dependency-tracking
    - make
    - make check
    - make install
